### ISSUE TITLE
Running as admin off a network path fails on Windows

### ISSUE THREAD

**Issue by abandonedaccount6235** [dyorgio/run-as-root#6]
Discovered via #5, this library will fail to run the code as admin if the classpath is located on a network drive. It seems that the JVM does not support mapped drive letters and requires the full UNC path for the `-cp` parameter  (e.g. `\\computer\share\folder` rather than a mapped `M:\folder`).

**Comment by dyorgio** [comment]
Hi @Pikachu920, checkout last version (1.2.2), it uses last version of out-process (with support to handling UNC paths). Please, give me a feedback after testing..

**Comment by abandonedaccount6235** [comment]
that fixed it! thank you very much for working with me on this one.

I do wonder, though: could we find a better way to resolve the UNC path besides using a `sun` class reflectively?

**Comment by dyorgio** [comment]
Maybe we can use a native executable call (net.exe use)[[stackoverflow](https://stackoverflow.com/questions/5722146/how-to-retrieve-the-unc-path-instead-of-mapped-drive-path-from-jfilechooser)]
But I prefer use reflection, because sun.awt package, and AWT at all, is very stable (+20 years without changing SPI and there is no other AWT "provider")

**Comment by dyorgio** [comment]
Oh, I tested with headless mode and worrks too :P

**Comment by abandonedaccount6235** [comment]
what about other JDKs? does openjdk support the sun classes?

**Comment by dyorgio** [comment]
Yes, I tested with oracle and openjdk ;), theses packages are included in last Java 14 version.
